# Generated by Django 4.2.30 on 2026-07-21 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Email subject line.', max_length=255)),
                ('body', models.TextField(help_text='Full email body content.')),
                ('tone', models.CharField(choices=[('Professional', 'Professional'), ('Friendly', 'Friendly'), ('Formal', 'Formal'), ('Casual', 'Casual')], default='Professional', help_text='Tone used when generating this email.', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('SENT', 'Sent')], default='DRAFT', help_text='Current status of this email draft.', max_length=10)),
                ('approved', models.BooleanField(default=False, help_text='Whether this draft has been approved for sending.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(help_text='The lead this email draft is targeting.', on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
