# Generated by Django 6.0.7 on 2026-07-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_campaign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('company_size', models.CharField(max_length=50)),
                ('keywords', models.TextField(help_text='Comma separated keywords')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.campaign')),
            ],
        ),
    ]
